package com.tkachuk.pet.utils;

public enum Notifications {
    NAME_UPDATED, PROFILE_PHOTO_UPDATED, PASSWORD_UPDATED, EMAIL_UPDATED, ROLE_UPDATED,
    EMAIL_UPDATED_BY_ADMINISTRATION, PASSWORD_UPDATED_BY_ADMINISTRATION, NAME_UPDATED_BY_ADMINISTRATION, ROLE_UPDATED_BY_ADMINISTRATION;
}
